import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import styles from '../../styles/Home.module.css'
import Navbar from '../../Component/navigation/page';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>  
      {/* <div className='mt-16 my-5'>
        <button className='text-white text-center'  >Sign In</button>
      </div> */}
    <body className={inter.className}>
      <Navbar />
      {children}
      {/* <Footer /> */}
      </body>
    </>
  )
}